### ISSUE TITLE
Swift Use

### ISSUE THREAD

**Issue by inceptiveKshitij** [cspnanda/CustomImagePicker#2]
How to use this library in swift

**Comment by cspnanda** [comment]
It is pretty easy. You need to create a bridging header. Please look at http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift for details. Then you can do something like

```
var cip:CustomeImagePicker = CustomeImagePicker();
self.presentViewController(cip, animated: true, completion: nil)
```

**Comment by inceptiveKshitij** [comment]
Which file are imported in bridge file
